name: terraform-config

on:
  pull_request: {}
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform format check
        id: fmt
        run: terraform fmt -check -recursive -diff

      - name: teraform lint
        id: tflint
        uses: devops-infra/action-tflint@0.3
